[project]
name = "quantization-adalora-speech-recognition"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "rich>=14.3.2",
    "torch==2.8.0",
    "torchao==0.9.0",
    "transformers>=4.57.6",
    "typer>=0.24.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cu126", marker = "sys_platform != 'darwin'"},
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'"},
]
torchao = [
  { index = "pytorch-cu126", marker = "sys_platform != 'darwin'"},
  { index = "pytorch-cpu", marker = "sys_platform == 'darwin'"},
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
